<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_593905804422c',
	'title' => 'Metadata för evenemang',
	'fields' => array (
		array (
			'key' => 'field_593905da7892b',
			'label' => 'Call to action - Text',
			'name' => 'call_to_action_text',
			'type' => 'text',
			'instructions' => 'Text på knapp i kalendariet, till exempel "Köp biljett direkt" eller "Boka bord"',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_593906687892c',
			'label' => 'Call to action - Länk',
			'name' => 'call_to_action_link',
			'type' => 'text',
			'instructions' => 'Länk för "Call to action", till exempel till bokningsformulär.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_593906d67892d',
			'label' => 'Längd',
			'name' => 'duration_text',
			'type' => 'text',
			'instructions' => 'Evenemangets ungefärliga längd beskrivet i fritext.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5939074b7892e',
			'label' => 'Biljettpris',
			'name' => 'price_html',
			'type' => 'wysiwyg',
			'instructions' => 'Information om priset beskrivet i fritext.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
		array (
			'key' => 'field_593907a87892f',
			'label' => 'Övrigt',
			'name' => 'other_text',
			'type' => 'text',
			'instructions' => 'Övrig information, till exempel åldersgräns.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_593907fa78930',
			'label' => 'Arrangör',
			'name' => 'organizer_text',
			'type' => 'text',
			'instructions' => 'Information om vem som arrangerar evenemanget beskrivet i fritext.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_593a62bce8bdf',
			'label' => 'Lokal',
			'name' => 'venue_text',
			'type' => 'text',
			'instructions' => 'Lokalen där evenemanget kommer hållas.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5939081d78931',
			'label' => 'Medverkande',
			'name' => 'performers_text',
			'type' => 'text',
			'instructions' => 'Information om medverkande, till exempel artister, som fritext.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5939095d1be66',
			'label' => 'Tillfällen',
			'name' => 'occurrences',
			'type' => 'repeater',
			'instructions' => 'Datum och tider för evenemanget.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_593909e71be67',
					'label' => 'Startdatum & tid',
					'name' => 'startdate',
					'type' => 'date_time_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'Y-m-d H:i:s',
					'return_format' => 'Y-m-d H:i:s',
					'first_day' => 1,
				),
				array (
					'key' => 'field_593a627ce8bde',
					'label' => 'Slutdatum & tid',
					'name' => 'enddate',
					'type' => 'date_time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'Y-m-d H:i:s',
					'return_format' => 'Y-m-d H:i:s',
					'first_day' => 1,
				),
				array (
					'key' => 'field_593a5b8e981ce',
					'label' => 'URL till bokning',
					'name' => 'url',
					'type' => 'text',
					'instructions' => 'URL till bokningsformulär för detta tillfälle.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'event',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_593a608abfd76',
	'title' => 'Metadata för eventkategori',
	'fields' => array (
		array (
			'key' => 'field_593a60a280cbc',
			'label' => 'Sorteringsordning',
			'name' => 'eventcat_order',
			'type' => 'number',
			'instructions' => 'Sorteringsnummer för kategorin under Upptäck & upplev.
Lågt nummer = Högt upp i listan.
Högt nummer = Långt ner i listan.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 10,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_593ea5de9fd67',
			'label' => 'Utvald bild',
			'name' => 'featured_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'eventcat',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
?>